
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action Action;
	
	private global::Gtk.VBox vbox10;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.FileChooserButton filechooserbutton2;
	
	private global::Gtk.Label GtkLabel2;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.VBox vbox9;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview5;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.VBox vbox16;
	
	private global::Gtk.VBox vbox17;
	
	private global::Gtk.Label GtkLabel3;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.RadioButton radiobutton6;
	
	private global::Gtk.RadioButton radiobutton7;
	
	private global::Gtk.RadioButton radiobutton8;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.RadioButton radiobutton9;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.VBox vbox14;
	
	private global::Gtk.VBox vbox18;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry entry3;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.FileChooserButton filechooserbutton4;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.VBox vbox15;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.VBox vbox21;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.VBox vbox11;
	
	private global::Gtk.VBox vbox12;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView textview7;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.ProgressBar progressbar4;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		this.openAction.ShortLabel = "";
		w1.Add (this.openAction, null);
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		this.Action.ShortLabel = "";
		w1.Add (this.Action, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Securish");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(8));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='Action' action='Action'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox10.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.filechooserbutton2 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton2.WidthRequest = 200;
		this.filechooserbutton2.Name = "filechooserbutton2";
		this.vbox4.Add (this.filechooserbutton2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.filechooserbutton2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Import File</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView ();
		this.textview5.HeightRequest = 250;
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.GtkScrolledWindow.Add (this.textview5);
		this.vbox9.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow]));
		w8.Position = 0;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox16 = new global::Gtk.VBox ();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		this.vbox13.Add (this.vbox16);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox16]));
		w9.Position = 0;
		// Container child vbox13.Gtk.Box+BoxChild
		this.vbox17 = new global::Gtk.VBox ();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		this.vbox13.Add (this.vbox17);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox17]));
		w10.Position = 1;
		this.vbox9.Add (this.vbox13);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox13]));
		w11.Position = 1;
		this.GtkAlignment1.Add (this.vbox9);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Import Text</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel3;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w14.Position = 1;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.WidthRequest = 200;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose Cryptogtaphy Technique");
		this.vbox6.Add (this.label1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.radiobutton6 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Substitution"));
		this.radiobutton6.CanFocus = true;
		this.radiobutton6.Name = "radiobutton6";
		this.radiobutton6.DrawIndicator = true;
		this.radiobutton6.UseUnderline = true;
		this.radiobutton6.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox7.Add (this.radiobutton6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobutton6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.radiobutton7 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Transposition"));
		this.radiobutton7.CanFocus = true;
		this.radiobutton7.Name = "radiobutton7";
		this.radiobutton7.DrawIndicator = true;
		this.radiobutton7.UseUnderline = true;
		this.radiobutton7.Group = this.radiobutton6.Group;
		this.vbox7.Add (this.radiobutton7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobutton7]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.radiobutton8 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Vernam"));
		this.radiobutton8.CanFocus = true;
		this.radiobutton8.Name = "radiobutton8";
		this.radiobutton8.DrawIndicator = true;
		this.radiobutton8.UseUnderline = true;
		this.radiobutton8.Group = this.radiobutton6.Group;
		this.vbox7.Add (this.radiobutton8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobutton8]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox6.Add (this.vbox7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox7]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox2.Add (this.vbox6);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox6]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.radiobutton9 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Vigenere"));
		this.radiobutton9.CanFocus = true;
		this.radiobutton9.Name = "radiobutton9";
		this.radiobutton9.DrawIndicator = true;
		this.radiobutton9.UseUnderline = true;
		this.radiobutton9.Group = this.radiobutton6.Group;
		this.vbox8.Add (this.radiobutton9);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.radiobutton9]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox8.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator1]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox14 = new global::Gtk.VBox ();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.vbox18 = new global::Gtk.VBox ();
		this.vbox18.Name = "vbox18";
		this.vbox18.Spacing = 6;
		// Container child vbox18.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Provide Key:");
		this.vbox18.Add (this.label6);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.label6]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox18.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox18.Add (this.entry3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.entry3]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox14.Add (this.vbox18);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox18]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Keyfile:");
		this.vbox14.Add (this.label7);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.label7]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.filechooserbutton4 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton4.Name = "filechooserbutton4";
		this.vbox14.Add (this.filechooserbutton4);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.filechooserbutton4]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox8.Add (this.vbox14);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox14]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox2.Add (this.vbox8);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox8]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox ();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.WidthRequest = 200;
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Operation");
		this.vbox15.Add (this.label8);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.label8]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.vbox21 = new global::Gtk.VBox ();
		this.vbox21.Name = "vbox21";
		this.vbox21.Spacing = 6;
		// Container child vbox21.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Encrypt");
		this.vbox21.Add (this.button4);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.button4]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox21.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Decrypt");
		this.vbox21.Add (this.button5);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.button5]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox21.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Test");
		this.vbox21.Add (this.button6);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.button6]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox15.Add (this.vbox21);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.vbox21]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox3.Add (this.vbox15);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox15]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w38.Position = 2;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.WidthRequest = 200;
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
		this.vbox12.Add (this.label2);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label2]));
		w39.Position = 0;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview7 = new global::Gtk.TextView ();
		this.textview7.WidthRequest = 160;
		this.textview7.CanFocus = true;
		this.textview7.Name = "textview7";
		this.GtkScrolledWindow1.Add (this.textview7);
		this.vbox12.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.GtkScrolledWindow1]));
		w41.Position = 1;
		this.vbox11.Add (this.vbox12);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
		w42.Position = 0;
		// Container child vbox11.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Clear Log");
		global::Gtk.Image w43 = new global::Gtk.Image ();
		w43.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
		this.button1.Image = w43;
		this.vbox11.Add (this.button1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.button1]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		this.hbox1.Add (this.vbox11);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox11]));
		w45.Position = 3;
		w45.Expand = false;
		w45.Fill = false;
		this.vbox10.Add (this.hbox1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox1]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.progressbar4 = new global::Gtk.ProgressBar ();
		this.progressbar4.Name = "progressbar4";
		this.vbox10.Add (this.progressbar4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.progressbar4]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.Add (this.vbox10);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 848;
		this.DefaultHeight = 589;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
