
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Frame frame8;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox10;
	private global::Gtk.Frame frame9;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label1;
	private global::Gtk.Entry txt_plaintext_input;
	private global::Gtk.Label label2;
	private global::Gtk.Button btn_file_input;
	private global::Gtk.Label GtkLabel1;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.ComboBox cmb_algorithm;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.ComboBox cmb_mode;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.Frame frame10;
	private global::Gtk.Alignment GtkAlignment5;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label3;
	private global::Gtk.Entry txt_keytext_input;
	private global::Gtk.Label label4;
	private global::Gtk.SpinButton spb_shift;
	private global::Gtk.Label GtkLabel6;
	private global::Gtk.Button btn_Go;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment9;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txt_log;
	private global::Gtk.Label GtkLabel9;
	private global::Gtk.Label GtkLabel10;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Securish");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame8 = new global::Gtk.Frame ();
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame8.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame9 = new global::Gtk.Frame ();
		this.frame9.Name = "frame9";
		this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame9.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Text:");
		this.hbox11.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.txt_plaintext_input = new global::Gtk.Entry ();
		this.txt_plaintext_input.CanFocus = true;
		this.txt_plaintext_input.Name = "txt_plaintext_input";
		this.txt_plaintext_input.IsEditable = true;
		this.txt_plaintext_input.InvisibleChar = '●';
		this.hbox11.Add (this.txt_plaintext_input);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.txt_plaintext_input]));
		w2.Position = 1;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Select File:");
		this.hbox11.Add (this.label2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label2]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.btn_file_input = new global::Gtk.Button ();
		this.btn_file_input.CanFocus = true;
		this.btn_file_input.Name = "btn_file_input";
		this.btn_file_input.UseUnderline = true;
		// Container child btn_file_input.Gtk.Container+ContainerChild
		global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w5 = new global::Gtk.HBox ();
		w5.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_folder", global::Gtk.IconSize.Button);
		w5.Add (w6);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w8 = new global::Gtk.Label ();
		w8.LabelProp = global::Mono.Unix.Catalog.GetString ("Open File");
		w8.UseUnderline = true;
		w5.Add (w8);
		w4.Add (w5);
		this.btn_file_input.Add (w4);
		this.hbox11.Add (this.btn_file_input);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btn_file_input]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.GtkAlignment1.Add (this.hbox11);
		this.frame9.Add (this.GtkAlignment1);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Provide Input Plaintext or File:</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame9.LabelWidget = this.GtkLabel1;
		this.vbox10.Add (this.frame9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame9]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.cmb_algorithm = global::Gtk.ComboBox.NewText ();
		this.cmb_algorithm.AppendText (global::Mono.Unix.Catalog.GetString ("Substitution"));
		this.cmb_algorithm.AppendText (global::Mono.Unix.Catalog.GetString ("Vernam"));
		this.cmb_algorithm.AppendText (global::Mono.Unix.Catalog.GetString ("Transposition"));
		this.cmb_algorithm.AppendText (global::Mono.Unix.Catalog.GetString ("Vigenere"));
		this.cmb_algorithm.Name = "cmb_algorithm";
		this.cmb_algorithm.Active = 0;
		this.GtkAlignment3.Add (this.cmb_algorithm);
		this.frame1.Add (this.GtkAlignment3);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Select Cryptography Algorithm:</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel3;
		this.vbox10.Add (this.frame1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.cmb_mode = global::Gtk.ComboBox.NewText ();
		this.cmb_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Encryption"));
		this.cmb_mode.AppendText (global::Mono.Unix.Catalog.GetString ("Decryption"));
		this.cmb_mode.Name = "cmb_mode";
		this.cmb_mode.Active = 0;
		this.GtkAlignment4.Add (this.cmb_mode);
		this.frame2.Add (this.GtkAlignment4);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Select Mode:</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.vbox10.Add (this.frame2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame2]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame10 = new global::Gtk.Frame ();
		this.frame10.Name = "frame10";
		this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame10.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter Text:");
		this.hbox12.Add (this.label3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label3]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.txt_keytext_input = new global::Gtk.Entry ();
		this.txt_keytext_input.CanFocus = true;
		this.txt_keytext_input.Name = "txt_keytext_input";
		this.txt_keytext_input.IsEditable = true;
		this.txt_keytext_input.InvisibleChar = '●';
		this.hbox12.Add (this.txt_keytext_input);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.txt_keytext_input]));
		w23.Position = 1;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Shift Value (for substitution)");
		this.hbox12.Add (this.label4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label4]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.spb_shift = new global::Gtk.SpinButton (0, 100, 1);
		this.spb_shift.CanFocus = true;
		this.spb_shift.Name = "spb_shift";
		this.spb_shift.Adjustment.PageIncrement = 10;
		this.spb_shift.ClimbRate = 1;
		this.spb_shift.Numeric = true;
		this.spb_shift.Value = 1;
		this.hbox12.Add (this.spb_shift);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.spb_shift]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.GtkAlignment5.Add (this.hbox12);
		this.frame10.Add (this.GtkAlignment5);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Provide Key Text:</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame10.LabelWidget = this.GtkLabel6;
		this.vbox10.Add (this.frame10);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame10]));
		w28.Position = 3;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.btn_Go = new global::Gtk.Button ();
		this.btn_Go.CanFocus = true;
		this.btn_Go.Name = "btn_Go";
		this.btn_Go.UseUnderline = true;
		// Container child btn_Go.Gtk.Container+ContainerChild
		global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w30 = new global::Gtk.HBox ();
		w30.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w31 = new global::Gtk.Image ();
		w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
		w30.Add (w31);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w33 = new global::Gtk.Label ();
		w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Go!");
		w33.UseUnderline = true;
		w30.Add (w33);
		w29.Add (w30);
		this.btn_Go.Add (w29);
		this.vbox10.Add (this.btn_Go);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btn_Go]));
		w37.Position = 4;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment9 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment9.Name = "GtkAlignment9";
		this.GtkAlignment9.LeftPadding = ((uint)(12));
		// Container child GtkAlignment9.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txt_log = new global::Gtk.TextView ();
		this.txt_log.CanFocus = true;
		this.txt_log.Name = "txt_log";
		this.GtkScrolledWindow.Add (this.txt_log);
		this.GtkAlignment9.Add (this.GtkScrolledWindow);
		this.frame4.Add (this.GtkAlignment9);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output:</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel9;
		this.vbox10.Add (this.frame4);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame4]));
		w41.Position = 5;
		this.GtkAlignment.Add (this.vbox10);
		this.frame8.Add (this.GtkAlignment);
		this.GtkLabel10 = new global::Gtk.Label ();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Select Options:</b>");
		this.GtkLabel10.UseMarkup = true;
		this.GtkLabel10.Justify = ((global::Gtk.Justification)(2));
		this.frame8.LabelWidget = this.GtkLabel10;
		this.Add (this.frame8);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btn_file_input.Clicked += new global::System.EventHandler (this.OnBtnFileInputClicked);
		this.cmb_algorithm.Changed += new global::System.EventHandler (this.OnCmbAlgorithmChanged);
		this.cmb_mode.Changed += new global::System.EventHandler (this.OnCmbModeChanged);
		this.btn_Go.Clicked += new global::System.EventHandler (this.OnBtnGoClicked);
	}
}
